{\rtf1\ansi\ansicpg1252\cocoartf1504\cocoasubrtf810
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww22900\viewh16560\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf0 \expnd0\expndtw0\kerning0
JFLAGS = -g\
JC = javac\
.SUFFIXES: .java .class\
.java.class:\
        $(JC) $(JFLAGS) $*.java\
\
CLASSES = \\\
        Driver.java \\\
        Student.java \\\
        Address.java \\\
        Stack.java \
\
default: classes\
\
classes: $(CLASSES:.java=.class)\
\
clean:\
        $(RM) *.class}